id: PBB4DB7A6
initial_creation_type: input
source_metadata:
  title: Khenpo Gangshar Wangpo
  language: fr
  description: 'Texts by the Dzogchen teacher Khenpo Gangshar Wangpo (mkhan po gang
    shar dbang po, 1925–1958/9), who is known especially for his role as the root
    teacher of Chögyam Trungpa:'
  volume:
    f5a3a8f541bd4e42893015aa3d1d4c96:
      title: A Way of Settling into the Realization of Mind’s Essence
      parent: Advice
    55760c5e25d348a9bb22700ead8688c1:
      title: A Song of Advice for Gok Zangden
      parent: Dzogchen
    f0bab13f3af1485da141f9cd4a7d8a4c:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Dzogchen
    28c9ef84a6974475afae8e383a776226:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Dzogchen
    9b86195b74ec4495af8cf8765af72e1d:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Dzogchen
    f971f0a0414a4c15a24929a9ce667277:
      title: 'Vomiting Gold: A Pith Instruction in the Form of Advice for the Diligent
        Practitioner, the Excellent Atsang'
      parent: Dzogchen
    8750e2a24ebb400b904e29e734aed94b:
      title: 'Guru Yoga: The Consummate Blessing'
      parent: Guru Yoga
    d3da6afb366b4678b86918c5582db79a:
      title: 'From the Mahāmudrā Preliminary Practices: Continuous Integration with
        Ground, Path, and Fruition'
      parent: Mahāmudrā
    46bbb258ace84b6bbac6976c41c3a219:
      title: Prayer to Pacify Military Conflict
      parent: Prayers
created_at: '2022-03-01T00:25:04.700171'
last_modified_at: '2022-03-01T00:25:04.700174'
